// English defaults for the workflow editor; a host supplies translations through UIProvider.

import { useMemo } from 'react'
import { useStrings } from '../components/Provider'
import type { EditRefusalReason } from '../editing'

export const GRAPH_EDITOR_STRINGS = {
  undo: 'Undo',
  redo: 'Redo',
  addJob: 'Job',
  addJobHint: 'Drag into the graph to add a job, or click to add one',
  addMatrixJob: 'Matrix job',
  addMatrixJobHint: 'Drag into the graph to add a matrix job, or click to add one',
  resetLayout: 'Reset layout',
  dropToDelete: 'Drop here to delete',
  jobActions: 'Job actions',
  stepActions: 'Step actions',
  stepCount: (count: number) => (count === 1 ? '1 step' : `${count} steps`),
  problemCount: (count: number) => (count === 1 ? '1 problem' : `${count} problems`),
  problemLine: (line: number) => `Line ${line}`,
  connectOutHint:
    'Drag onto a job to make it depend on this node. Drop on a circle to cover every job in that node.',
  connectInHint:
    'Drag onto a job to make this node depend on it. Drop on a circle to cover every job in that node.',
  moveBoxHint: 'Drag to move these jobs together',
  moveSelectionHint: 'Drag to move the selected jobs together',
  selectionOutHint:
    'Drag onto a job to make it depend on the selected jobs. Drop on a circle to cover every job there.',
  selectionInHint:
    'Drag onto a job to make the selected jobs depend on it. Drop on a circle to cover every job there.',
  duplicate: 'Duplicate',
  makeMatrix: 'Make matrix',
  editMatrix: 'Edit matrix',
  removeMatrix: 'Remove matrix',
  addStep: 'Add step',
  deleteJob: 'Delete job',
  deleteStep: 'Delete step',
  removeDependency: 'Remove dependency',
  dependencyInUse: "An expression in the job reads this dependency's outputs",
  dependency: 'Dependency',
  dependencyOf: (from: string, to: string) => `${to} depends on ${from}`,
  // Left to refusalText, which falls back to the engine's English wording.
  refusal: (_reason: EditRefusalReason): string => '',
  menuDependsOn: 'Depends on',
  menuNeededBy: 'Needed by',
  shortcuts: 'Shortcuts',
  shortcutGroups: { select: 'Select', change: 'Change', view: 'View' },
  shortcutKeys: {
    click: 'Click',
    drag: 'Drag',
    dragJob: 'Drag a job',
    dragCircle: 'Drag a circle',
    dragButton: 'Drag a button',
    dragSpace: 'Drag empty space',
    dragHandle: 'Drag a handle',
    dragEdge: 'Drag the edge between two inputs',
    rightClick: 'Right-click',
    scroll: 'Scroll',
    shift: 'Shift',
    enter: 'Enter',
    delete: 'Delete',
  },
  shortcutDoes: {
    select: 'Add a job, step or dependency to the selection, one kind at a time',
    box: 'Select with a box drawn on empty space: jobs if it reaches any, else steps, else dependencies',
    pan: 'Pan',
    zoom: 'Zoom',
    move: 'Move the job or the selection; a grip moves its node. Drop on another node to group them',
    connect: 'Connect the node to a job or another circle',
    addJob: 'Add a job or matrix job where you drop it',
    edit: "Open the selected job's or step's settings",
    dependency: 'Select a dependency, then drag its ends to move it',
    menu: 'Menu of a job, step or dependency',
    remove: 'Delete the selection',
    nudge: 'Nudge the selected jobs',
    copy: 'Copy or paste the selected jobs or steps',
    undo: 'Undo or redo',
    escape: 'Clear the selection or cancel a drag',
    focus: 'Move between jobs and dependencies',
    pickJob: 'Select the focused job',
    pickDependency: 'Select the focused dependency',
    moveInput:
      'Move the input, or all the selected ones. Drop on another input’s left or right side to put them side by side, or on its lower half to go under it',
    resizeInputs: 'Change how much of the line each input takes',
    pickInput: 'Select the input above, below or beside',
    extendInputs: 'Add each input passed to the selection',
    reorderInputs: 'Move the selected inputs up or down',
    addInput: 'Add an input where you drop it',
    editInput: "Open the selected input's settings",
    inputMenu: 'Menu of an input',
    selectInput: 'Add an input to the selection',
    boxInputs: 'Select inputs with a box',
    removeInputs: 'Delete the selected inputs',
  },
  moveDependencyEnd: 'Drag onto another job or node to move this end',
  openOnAdd: 'Open when adding',
  openOnAddHelp:
    "Adding a job, step or input opens this editor first. Off, it's added with its defaults, for you to edit later.",
  waitForAny: 'Wait for any matrix instance',
  matrixBadge: 'matrix',
  jobName: 'Job name',
  stepName: 'Step name',
  invalidJobName: 'Use only lowercase letters, numbers, dashes, and underscores.',
  jobExists: 'A job with this name already exists.',
  matrixVariable: 'Variable',
  matrixValues: 'Values, separated by commas',
  addVariable: 'Add variable',
  removeVariable: 'Remove variable',
  save: 'Save',
  cancel: 'Cancel',
  editJob: 'Edit job',
  editStep: 'Edit step',
  sectionDependencies: 'Dependencies and condition',
  sectionRemoteHost: 'Remote host',
  sectionMatrix: 'Matrix',
  sectionEnvironment: 'Environment variables',
  sectionOutputs: 'Outputs',
  sectionAdvanced: 'Advanced',
  sectionBehavior: 'Condition and behavior',
  sectionRetry: 'Retry',
  sectionCleanup: 'Cleanup',
  noOtherJobs: 'There are no other jobs to depend on.',
  dependsOnThisJob: 'That job already depends on this one.',
  missingJob: 'not found',
  runsInWorkspace: 'Leave Host empty to run in your workspace.',
  sectionComputeEnvironment: 'Compute environment',
  runsOnHint: 'Run this job as a scheduler job on a compute environment, without your workspace.',
  runsOnNeedsEnvironment: 'Fill in both the cluster and the environment name.',
  runsOnByName: 'Environment by name',
  runsOnByTarget: 'Compute target',
  runsOnNeedsMode: 'Choose where the job runs: a login node, an environment or a worker.',
  targetModes: { login: 'Login node', environment: 'Environment', worker: 'Worker' },
  runsOnWithSsh:
    'A job runs on a compute environment or on a remote host, not both. Clear one of them.',
  matrixOn: 'Run once for every combination of values.',
  matrixNeedsVariable: 'Add at least one variable.',
  matrixInvalidVariable: 'Each variable needs a unique name and at least one value.',
  invalidMaxParallel: 'Use a whole number of 1 or more.',
  invalidDuration: 'Use seconds (300) or a duration such as 30s, 10m or 2h.',
  invalidExpressionValue: 'Type an expression here, such as one that reads an input.',
  invalidEnvKey: 'Use letters, numbers, and underscores.',
  invalidKey: 'Use letters, numbers, dashes, and underscores.',
  duplicateKey: 'Each key must be unique.',
  remoteHostRequired: 'Fill in Host to connect to a remote machine.',
  key: 'Key',
  value: 'Value',
  addRow: 'Add',
  removeRow: 'Remove',
  /** A list's row, by the list's name and its place in it. */
  listItem: (list: string, n: number) => `${list}, item ${n}`,
  stepRun: 'Run commands',
  stepUses: 'Use a workflow or action',
  required: 'Required.',
  invalidShell: 'Use a bash or sh command.',
  missingInput: (name: string) => `Add the ${name} input.`,
  invalidCount: 'Use a whole number.',
  moveUp: 'Move up',
  moveDown: 'Move down',
  sshInherit: 'Same as the job',
  sshCustom: 'Another host',
  sshNone: 'Your workspace',
  workflowSettings: 'Workflow settings',
  invalidJson: 'Use valid JSON.',
  jsonValue: 'A nested value, written as JSON',
  matrixFromVariables: 'Variables',
  matrixFromExpression: 'Expression',
  addEntry: 'Add entry',
  removeEntry: 'Remove entry',
  invalidMatrixEntry: 'Each entry needs at least one key.',
  sectionGeneral: 'General',
  sectionPermissions: 'Permissions',
  sectionSessions: 'Sessions',
  sectionLinks: 'Links',
  sectionRequiredVariables: 'Required variables',
  sectionInputForm: 'Input form',
  addPermission: 'Add permission',
  addSession: 'Add session',
  addLink: 'Add link',
  addOrganizationVariable: 'Add organization variable',
  addUserVariable: 'Add user variable',
  sessionTypeTunnel: 'Tunnel',
  sessionTypeLink: 'Link',
  promptOff: 'Don’t ask',
  promptAsk: 'Ask for a name',
  linkToEndpoint: 'An endpoint session',
  linkToUrl: 'An address',
  invalidLinkName:
    'Use lowercase letters, numbers, dashes, and underscores, ending in a letter or number.',
  invalidOrganizationVariable:
    'Use uppercase letters, numbers, and underscores, starting with a letter.',
  oneRedirect: 'Only one session or link can redirect.',
  labelsBeside: 'Beside the fields',
  labelsAbove: 'Above the fields',
  notActionInput: 'Not an input this takes. Remove it.',
  invalidNumberInput: 'Use a number.',
  invalidChoice: (name: string) => `Use one of the listed values for ${name}.`,
  invalidUses:
    'Use workflow/NAME, marketplace/NAME, a github/ or gitlab/ address, or a built-in action.',
  chooseInput: 'Choose an input',
  noMatchingInputs: 'No inputs of this kind yet',
  newInput: 'New input…',
  newInputOf: (type: string) => `New ${type} input…`,
  conditionNever: 'Never',
  useExpression: 'Use an expression instead',
  stopExpression: 'Back to the regular field',
  whenOn: (label: string) => `When ${label} is on`,
  whenOff: (label: string) => `When ${label} is off`,
  whenIs: (label: string, option: string) => `When ${label} is ${option}`,
  insertValue: 'Insert a value…',
  applyFix: (text: string) => `Use ${text}`,
  refGroups: {
    inputs: 'Inputs',
    outputs: 'Outputs of jobs it needs',
    matrix: 'Matrix values',
    variables: 'Variables',
    sessions: 'Sessions',
    env: 'Environment',
  },
  stepConditions: {
    default: 'After the steps before it succeed',
    always: 'Always, even after a failure or a cancel',
    failure: 'Only after a step failed',
    cancelled: 'Only after the run was canceled',
    success: 'Only if nothing failed or was canceled',
  },
  jobConditions: {
    default: 'After the jobs it needs succeed',
    always: 'Always, whatever the jobs it needs did',
    failure: 'Only if a job it needs failed',
    cancelled: 'Only if a job it needs was canceled',
    success: 'Only if every job it needs succeeded',
  },
  modeFromInput: 'From an input',
  clearValue: 'Clear',
  matrixValuesListed: 'Listed values',
  outputName: 'Name',
  outputStep: 'Step',
  outputKey: 'Output',
  outputValue: 'Value',
  outputNeedsStep: 'Pick a step and name one of its outputs.',
  noStepIds: 'To hand on a step’s outputs, first give it a step ID in its Advanced settings.',
  usesAction: 'Action',
  usesWorkflow: 'My workflow',
  usesMarketplace: 'Marketplace',
  usesRepository: 'Repository',
  chooseAction: 'Choose an action',
  chooseWorkflow: 'Choose a workflow',
  chooseMarketplace: 'Choose a marketplace workflow',
  otherInputs: 'Other inputs',
  viewForm: 'Form',
  viewYaml: 'YAML',
  fixFieldsFirst: 'Fix the fields with errors first, so the YAML shows everything you entered.',
  yamlSyntax: (message: string) => `The YAML doesn’t parse: ${message}`,
  yamlNotMap: 'Write the settings as keys and values, such as run: make.',
  fields: {
    needs: 'Depends on',
    condition: 'When to run',
    remoteHost: 'Host',
    remoteUser: 'User',
    jumpNodeHost: 'Jump host',
    jumpNodeUser: 'Jump host user',
    disconnectTimeout: 'Disconnect timeout',
    runsOn: 'Environment',
    environmentCluster: 'Cluster',
    environmentName: 'Environment name',
    schedulingParams: 'Scheduling parameters',
    targetMode: 'Runs on',
    targetId: 'Target',
    environmentId: 'Environment ID',
    newWorker: 'New worker',
    workerId: 'Worker ID',
    matrix: 'Run as a matrix',
    matrixSource: 'Matrix source',
    matrixExpression: 'Matrix expression',
    include: 'Extra combinations',
    exclude: 'Skipped combinations',
    failFast: 'Stop others on a failure',
    maxParallel: 'Runs at the same time',
    workingDirectory: 'Folder to run in',
    timeout: 'Time limit',
    run: 'Commands',
    uses: 'Workflow or action',
    with: 'Inputs',
    cleanup: 'Cleanup commands',
    ignoreErrors: 'Keep going if it fails',
    earlyCancel: 'Stop if any job fails',
    retry: 'Try again if it fails',
    maxRetries: 'Number of retries',
    retryInterval: 'Wait between attempts',
    retryTimeout: 'Time limit per attempt',
    cleanOnRetry: 'Start each retry clean',
    stepId: 'Step ID',
    shell: 'Shell',
    env: 'Environment variables',
    name: 'Name',
    sessionType: 'Type',
    promptForName: 'Ask for a name',
    promptDefault: 'Suggested name',
    redirect: 'Open when the run starts',
    useTLS: 'Use HTTPS',
    useCustomDomain: 'Use a custom domain',
    openAI: 'OpenAI-compatible API',
    detach: 'Keep after the run',
    linkTarget: 'Link to',
    organizationVariables: 'Organization variables',
    userVariables: 'User variables',
    labelPosition: 'Where labels go',
    wizard: 'Split into pages',
    showSteps: 'Show page progress',
    allowJump: 'Allow going back',
    hideStepNumbers: 'Hide page numbers',
    submitLabel: 'Last button text',
    flatten: 'Leave out page names',
  },
  help: {
    jobName:
      'Lowercase letters, numbers, dashes and underscores. Other jobs use this name to depend on this one.',
    needs:
      'This job starts only after these jobs finish successfully. If one of them fails, this job is skipped.',
    waitForAny:
      'Start when the first run of that matrix job finishes, instead of waiting for all of them.',
    needsExpression:
      'An expression that works out which jobs this one waits for when the run starts.',
    jobIf:
      'Leave empty to run once the jobs it depends on succeed. Pick a choice from the list, such as always or only after a failure, or type your own condition.',
    remoteHost:
      'The machine to run on over SSH. Pick a cluster input from the list, or type a hostname or IP address.',
    remoteUser: 'The account to log in as. Leave empty to use your username.',
    jumpNodeHost:
      'A machine to connect through first, when the remote machine can’t be reached directly. Leave empty to connect directly.',
    jumpNodeUser: 'The account to log in to the jump host as. Leave empty to use your username.',
    disconnectTimeout:
      'How long to keep trying to reconnect if the connection drops, such as 300 or 5m. 0 gives up at once, and a negative number never gives up. The default is 5 minutes.',
    runsOn:
      'The compute environment this job runs on. Switch to an expression to work it out when the run starts.',
    environmentCluster:
      'The cluster the environment is on. For one shared with you, put its owner first, as owner/cluster.',
    environmentName: 'The environment’s name on that cluster.',
    schedulingParams:
      'Settings for the scheduler, such as walltime. They’re checked against the environment’s own, after its defaults.',
    targetMode:
      'A cluster’s login node, one of its environments, or one of its connected workers. A compute target input fills these in when the workflow is launched.',
    targetId: 'The cluster’s ID, or user-workspace for your workspace.',
    environmentId: 'For an environment: the ID of the environment to run in.',
    newWorker:
      'For an environment: start a new worker for this job instead of using one that’s running.',
    workerId: 'For a worker: the ID of the connected worker to run on.',
    matrixMode:
      'Type the values of each variable, or work the whole matrix out with an expression.',
    matrixVariables:
      'Give each variable a name and a list of values, separated by commas, or take them from a multi-select input. The job runs once for every combination: two variables with three values each make nine runs.',
    matrixExpression:
      'An expression that works out the whole matrix when the run starts, such as one that reads an input.',
    include:
      'Combinations to run on top of the ones the variables make. An entry that matches an existing combination adds its extra values to it instead.',
    exclude:
      'Combinations not to run. Any combination that matches every value in an entry is skipped.',
    failFast: 'When one run of the matrix fails, cancel the runs that are still going.',
    maxParallel: 'How many runs of the matrix can go at the same time. Leave empty for no limit.',
    jobEnv: 'Variables every step of this job can read from its environment, such as DATA_DIR.',
    outputs:
      'Values this job hands on to the jobs that depend on it, such as an output of one of its steps.',
    jobWorkingDirectory: 'The folder this job’s steps run in. It’s created if it doesn’t exist.',
    jobTimeout:
      'How long the job can run before it’s stopped and marked as failed, such as 300 (seconds), 10m or 2h.',
    stepName:
      'Shown in the graph and the run logs. If empty, the step’s command or workflow is shown.',
    stepKind: 'Run shell commands, or run another workflow or a built-in action.',
    run: 'The commands to run, as a shell script.',
    uses: 'What the step runs: a built-in action, one of your workflows, a marketplace workflow, or a workflow in a github/ or gitlab/ repository. Pick one from the list or type your own.',
    view: 'Edit these settings in the form, or as the YAML the workflow stores. Changes carry over when you switch.',
    with: 'The values passed to the workflow or action this step runs.',
    withInputs: 'The inputs that workflow asks for, by the names its form uses.',
    stepIf:
      'Leave empty to run once the steps before it succeed. Pick a choice from the list, such as always or only after a failure, or type your own condition.',
    stepTimeout:
      'How long the step can run before it’s stopped and marked as failed, such as 300 (seconds), 10m or 2h.',
    ignoreErrors: 'If the commands fail, mark the step as passed and carry on with the next one.',
    earlyCancel: 'Stop this step as soon as any other job in the run fails.',
    retry: 'Run the step again if it fails.',
    maxRetries: 'How many more times to try after the first failure. The default is 10.',
    retryInterval:
      'How long to wait before each new attempt, such as 5s or 1m. The default is 5 seconds.',
    retryTimeout: 'How long each attempt can run, such as 30s or 5m. The default is 30 seconds.',
    cleanOnRetry: 'Delete the step’s files before each new attempt so it starts fresh.',
    stepSsh: 'Where this step runs: on the job’s host, on another host, or in your workspace.',
    stepEnv: 'Variables this step can read from its environment, added to the job’s.',
    stepWorkingDirectory:
      'The folder this step runs in. It’s created if it doesn’t exist. If empty, the job’s folder is used.',
    stepId:
      'A short name other steps and jobs use to read this step’s outputs. It must be unique in the job.',
    shell: 'The program that runs the commands, such as bash -l. It must be bash or sh.',
    cleanup:
      'Commands that run when the job ends, if this step ran, even if a later step failed. Use it to remove temporary files or stop services.',
    workflowEnv: 'Variables every job and step of the workflow can read from its environment.',
    workflowTimeout: 'How long a whole run can take before it’s stopped, such as 30m or 2h.',
    permissions:
      'What the run’s API key is allowed to do, such as * for everything you can do. Users approve this before their first run.',
    sessions:
      'Interactive sessions the run opens, such as a web app on a cluster. The workflow’s steps fill in how to connect.',
    sessionName: 'The name the workflow’s steps use to update this session.',
    sessionType:
      'A tunnel connects to a port on a cluster. A link opens an address the workflow sets.',
    promptForName: 'Ask users to name the session before the run starts.',
    promptDefault: 'The name filled in for them.',
    sessionRedirect:
      'Open this session for the user as soon as the run starts. Only one session or link can do this.',
    useTLS: 'Connect to the session over HTTPS. Turn this on only if the app needs it.',
    useCustomDomain: 'Serve the session on its own domain. Turn this on only if the app needs it.',
    openAI: 'The session runs an AI model server, so connect it to the built-in chat.',
    sessionDetach: 'Keep the session open after the run ends, until someone deletes it.',
    links: 'Links shown on the run’s page, to sessions the workflow starts or to any web address.',
    linkName: 'Lowercase letters, numbers, dashes, and underscores, ending in a letter or number.',
    linkTarget: 'Link to a session the workflow starts, or straight to a web address.',
    linkEndpoint: 'The name of the session to link to. The link works once the session is up.',
    linkUrl: 'A web address starting with http or https. Without one, https is used.',
    linkRedirect:
      'Open this link for the user as soon as the run starts. Only one session or link can do this.',
    linkDetach: 'Keep the session this link points to open after the run ends.',
    organizationVariables:
      'Organization variables that must be set before anyone can run the workflow.',
    userVariables:
      'Your own variables the workflow reads. Users approve access before their first run.',
    userVariableHint: 'Why the workflow needs this variable. Users see it when asked for access.',
    labelPosition: 'Whether field names sit beside or above the fields on the input form.',
    wizard:
      'Show the input form one page at a time. Each input of the Wizard step type becomes a page.',
    showSteps: 'Show which page the user is on, above the form.',
    allowJump: 'Let users go back to pages they’ve already filled in.',
    hideStepNumbers: 'Hide the page numbers in the progress bar.',
    submitLabel: 'The text of the button on the last page. The default is Execute.',
    wizardFlatten:
      'On, the default: the workflow reads each field as inputs.FIELD. Off: as inputs.PAGE.FIELD, under its page’s name.',
  },
}

export type GraphEditorStrings = typeof GRAPH_EDITOR_STRINGS

export const INPUTS_EDITOR_STRINGS = {
  addInput: 'Input',
  addInputHint: 'Drag into the form to add an input, or click to pick its type',
  addInputHere: 'Add input',
  splitIntoPages: 'Split into pages',
  unsplitPages: 'Unsplit pages',
  addPage: 'Add a page after the last',
  page: 'Page',
  pageNumber: 'Page shown',
  /** The title of a wizard's `count`th page when the editor adds it. */
  stepTitle: (count: number) => `Step ${count}`,
  /** The submit button label of a form the editor splits into pages. */
  submitLabel: 'Submit',
  /** The label of the group a wizard step added outside a wizard comes in. */
  stepsGroup: 'Steps',
  addInputBelow: 'Add input below',
  addField: 'Add field',
  /** The add button ending a group's, page's or list row's fields, named by its label or title. */
  addFieldTo: (name: string) => `Add field to ${name}`,
  /** A repeatable page's title or description given per copy, as a list. */
  onePerCopy: 'One per copy',
  inputActions: 'Input actions',
  editInput: 'Edit input',
  duplicate: 'Duplicate',
  moveUp: 'Move up',
  moveDown: 'Move down',
  deleteInput: 'Delete input',
  hidden: 'hidden',
  noInputs: 'No inputs yet. Add one to build the form users fill in to run this workflow.',
  noFields: 'No fields yet.',
  inputName: 'Name',
  inputType: 'Type',
  invalidInputName: 'Use letters, numbers, dashes, and underscores.',
  inputExists: 'An input with this name already exists here.',
  invalidNumber: 'Use a number.',
  invalidDurationText: 'Use HH:MM:SS or D-HH:MM:SS.',
  invalidWidth: 'Use a number of pixels, such as 320, or a percentage, such as 50%.',
  resizeInputs: 'Resize the inputs on each side',
  sectionField: 'Field',
  sectionBehavior: 'Behavior',
  sectionSettings: 'Settings',
  optionValue: 'Value',
  optionLabel: 'Label',
  optionDescription: 'Description',
  addOption: 'Add option',
  removeOption: 'Remove option',
  addValue: 'Add value',
  searchTypes: 'Search types',
  noMatchingTypes: 'No matching types',
  optionsList: 'One list',
  optionsExpression: 'Expression',
  optionsByKey: 'Per value of another input',
  optionsJson: 'As JSON',
  optionsByKeyHelp:
    'For each value of the input the options depend on, list the options to show, as JSON.',
  optionsJsonHelp: 'These options have settings a list can’t show, so they’re edited as JSON.',
  impliesNeedsOptions: 'Add at least two options above to link them.',
  impliesWhen: (option: string) => `${option} also ticks`,
  choices: {
    optionLabelPosition: { left: 'Side by side', top: 'One per line' },
  },
  needsOptions: 'Add at least one option.',
  needsFields: 'Add at least one field.',
  optionsJsonShape: 'Use a JSON list of options.',
  optOutPlaceholder: 'Unlimited',
  optionsByKeyDropdownOnly: 'Only a dropdown takes options per value of another input. Use a list.',
  optionsByKeyShape: 'Use a JSON object that maps each key to a list of options.',
  jsonObject: 'Use a JSON object.',
  jsonObjectOrList: 'Use a JSON object or list.',
  typeChangeNote: 'Settings the new type doesn’t use are removed when you save.',
  flattenClash: (name: string) => `${name} is also the name of an input beside this group.`,
  disableNeedsBoth: 'Fill in both the checkbox text and its value.',
  keptValueDoesNotFit: 'This value doesn’t suit the new type. Change it or clear it.',
  wholeNumberFrom: (least: number) => `Use a whole number of ${least} or more.`,
  invalidPattern: 'Use a valid regular expression.',
  radioOptionShape: 'Each option is a text value, or a value and a label as text.',
  checkboxOptionShape:
    'Each option is a text value, or a value with a label and a description as text.',
  typeGroups: {
    basic: 'Basic',
    choices: 'Choices',
    layout: 'Layout',
    compute: 'Clusters and storage',
    schedulers: 'Schedulers',
    cloud: 'Cloud',
    kubernetes: 'Kubernetes',
    platform: 'Platform',
  },
  types: {
    string: 'Text',
    number: 'Number',
    duration: 'Duration',
    boolean: 'Switch',
    password: 'Password',
    editor: 'Code editor',
    'color-picker': 'Color',
    dropdown: 'Dropdown',
    'multi-dropdown': 'Multi-select',
    radio: 'Radio buttons',
    'checkbox-group': 'Checkboxes',
    group: 'Group',
    list: 'List',
    header: 'Header',
    step: 'Wizard step',
    'compute-clusters': 'Cluster',
    'compute-resources': 'Cluster or Kubernetes cluster',
    'compute-target': 'Compute target',
    bucket: 'Storage bucket',
    'slurm-accounts': 'Slurm account',
    'slurm-partitions': 'Slurm partition',
    'slurm-qos': 'Slurm QOS',
    'pbs-queues': 'PBS queue',
    region: 'Region',
    zone: 'Zone',
    'instance-type': 'Instance type',
    'organization-groups': 'Organization group',
    'ai-model': 'AI model',
    allocations: 'Allocation',
    'kubernetes-clusters': 'Kubernetes cluster',
    'kubernetes-namespaces': 'Namespace',
    'kubernetes-pods': 'Pod',
    'kubernetes-pvc': 'Persistent volume claim',
    'kubernetes-secrets': 'Secret',
    'kubernetes-configmaps': 'Config map',
    'kubernetes-statefulsets': 'Stateful set',
    'kubernetes-deployments': 'Deployment',
    'kubernetes-services': 'Service',
    'kubernetes-workloads': 'Workload',
  },
  typeHelp: {
    string: 'A line of text, or a larger text area.',
    number: 'A number, typed in or picked on a slider.',
    duration: 'A length of time typed as HH:MM:SS or D-HH:MM:SS. The run gets it in seconds.',
    boolean: 'An on or off switch.',
    password: 'Text that stays hidden as it is typed.',
    editor: 'A code editor for scripts or configuration files.',
    'color-picker': 'A color picker.',
    dropdown: 'Pick one value from a list of options.',
    'multi-dropdown': 'Pick any number of values from a list of options.',
    radio: 'Choices shown as radio buttons. The user picks one.',
    'checkbox-group':
      'Choices shown as checkboxes, each with an optional description. The user picks any.',
    group: 'A collapsible section of fields. Their values are nested under the group’s name.',
    list: 'Rows users add and remove, each with the same fields.',
    header: 'A heading that separates parts of the form. It has no value.',
    step: 'One page of fields when the form is shown as a wizard.',
    'compute-clusters': 'Pick one of the user’s clusters.',
    'compute-resources': 'Pick one of the user’s clusters or Kubernetes clusters.',
    'compute-target':
      'Pick where a job runs: the user’s workspace, a cluster’s login node, or one of its environments. A job runs there when its compute environment reads this input.',
    bucket: 'Pick one of the user’s storage buckets.',
    'slurm-accounts': 'Pick a Slurm account on a cluster.',
    'slurm-partitions': 'Pick a Slurm partition on a cluster.',
    'slurm-qos': 'Pick a Slurm quality of service on a cluster.',
    'pbs-queues': 'Pick a PBS queue on a cluster.',
    region: 'Pick a region of a cloud provider.',
    zone: 'Pick a zone in a cloud region.',
    'instance-type': 'Pick a machine type in a cloud region.',
    'organization-groups': 'Pick one of the organization’s groups.',
    'ai-model': 'Pick one of the AI models the user has access to.',
    allocations: 'Pick one of the allocations the user has access to.',
    'kubernetes-clusters': 'Pick a Kubernetes cluster.',
    'kubernetes-namespaces': 'Pick a namespace in a Kubernetes cluster.',
    'kubernetes-pods': 'Pick a pod in a namespace.',
    'kubernetes-pvc': 'Pick a persistent volume claim in a namespace.',
    'kubernetes-secrets': 'Pick a secret in a namespace.',
    'kubernetes-configmaps': 'Pick a config map in a namespace.',
    'kubernetes-statefulsets': 'Pick a stateful set in a namespace.',
    'kubernetes-deployments': 'Pick a deployment in a namespace.',
    'kubernetes-services': 'Pick a service in a namespace.',
    'kubernetes-workloads': 'Pick a workload in a namespace.',
  },
  fields: {
    label: 'Label',
    description: 'Description',
    tooltip: 'Tooltip',
    width: 'Width',
    'anchor-below': 'Below the input before it',
    optional: 'Optional',
    hidden: 'Hidden',
    disabled: 'Read-only',
    ignore: 'Leave out of the run',
    default: 'Default',
    placeholder: 'Hint text',
    textarea: 'Multiple lines',
    prefillDefault: 'Fill in the default',
    minLength: 'Shortest',
    maxLength: 'Longest',
    lowercase: 'Lowercase',
    sanitize: 'Characters to strip',
    min: 'Minimum',
    max: 'Maximum',
    step: 'Step size',
    slider: 'Slider',
    language: 'Language',
    options: 'Options',
    'option-key': 'Options depend on',
    autoselect: 'Select the first option',
    optionLabelPosition: 'Option layout',
    implies: 'Linked options',
    disableLabel: 'Checkbox text',
    disableValue: 'Value when ticked',
    optOut: 'Checkbox to turn it off',
    collapsed: 'Start folded',
    flatten: 'Leave out the group name',
    template: 'Row fields',
    'items-collapsible': 'Foldable rows',
    text: 'Text',
    size: 'Font size',
    bold: 'Bold',
    title: 'Title',
    nextLabel: 'Next button',
    prevLabel: 'Back button',
    'include-workspace': 'Offer the workspace',
    'include-unprovisioned': 'Offer clusters that are off',
    csp: 'Cloud provider',
    provider: 'Cluster types',
    multi: 'Multiple choices',
    multiStep: 'Repeatable page',
    generateCredentials: 'Generate credentials',
    region: 'Region',
    resource: 'Cluster',
    account: 'Account',
    partition: 'Partition',
    clusterName: 'Kubernetes cluster',
    namespace: 'Namespace',
    includeEmpty: 'Offer an empty choice',
  },
  help: {
    name: 'Letters, numbers, dashes and underscores. The workflow reads what users enter as inputs.NAME.',
    type: 'The kind of field users fill in.',
    label: 'The field’s name on the form. If empty, the input’s name is shown.',
    description: 'Help text shown under the field.',
    tooltip: 'Extra help shown when users hover over the field’s info icon.',
    width:
      'How wide the field is: a number of pixels, such as 320, or a share of the row, such as 50%. Fields whose widths fit side by side share a row. Empty means the full width.',
    'anchor-below':
      'Puts the field under the input before it, in that input’s column, when that input shares a row. It can be no wider than that input.',
    default: 'The value the field starts with.',
    defaultList: 'The values picked when the form opens.',
    defaultResource: 'What’s picked when the form opens, by its resource address.',
    defaultResources: 'What’s picked when the form opens, by resource address.',
    defaultFromInput: 'Start with the value of this other input.',
    durationDefault: 'The time the field starts with, as HH:MM:SS or D-HH:MM:SS.',
    optional: 'Let users leave the field empty. Use an expression to decide when.',
    hidden:
      'Hide the field from the form; its default is still used. Use an expression to decide when.',
    disabled: 'Show the field but don’t let users change it. Use an expression to decide when.',
    ignore: 'Don’t pass this field’s value to the run. Use an expression to decide when.',
    placeholder: 'Grey hint text shown while the field is empty.',
    prefillDefault:
      'Put the default in the field as its value. When off, the field starts empty and shows the default as grey hint text.',
    textarea: 'Show a bigger box for several lines of text.',
    minLength: 'The fewest characters the value can have.',
    maxLength: 'The most characters the value can have.',
    lowercase: 'Turn what users type into lowercase.',
    sanitize:
      'A regular expression matching the characters to remove as users type, such as [^a-z0-9-].',
    minNumber: 'The smallest value allowed.',
    maxNumber: 'The largest value allowed.',
    minDuration: 'The shortest length of time allowed.',
    maxDuration: 'The longest length of time allowed.',
    disableLabel: 'What the checkbox says, such as Never suspend idle nodes.',
    disableValue: 'What the workflow gets instead of a time while the box is ticked, such as -1.',
    optOut:
      'Adds a checkbox under the field. Ticking it hides the time and sends a fixed value instead, such as -1 for no limit.',
    step: 'How much the value goes up or down at a time, such as with the slider.',
    slider: 'Pick the value by dragging a slider. It needs a minimum, a maximum and a step size.',
    options:
      'The choices users pick from. Each has a value the workflow gets and, optionally, a label users see.',
    optionLabelPosition: 'Show the choices side by side, or one per line.',
    implies:
      'Choose which other options each one ticks with it. While an option is ticked, the ones it ticks stay ticked and can’t be unticked.',
    optionKey:
      'Another input whose value picks which options to show, such as a cloud provider picking its regions.',
    autoselect: 'Pick the first option for users when the form opens.',
    template: 'The fields each row has.',
    listDefault:
      'The rows the list starts with. Runs started from the form or the API both get them.',
    itemsCollapsible: 'Let users fold each row away.',
    minItems: 'The fewest rows users must add.',
    maxItems: 'The most rows users can add.',
    language: 'The language the editor colors code for, such as bash, python or yaml.',
    collapsed: 'Start with the group folded away. Use an expression to decide when.',
    flatten: 'Pass the group’s fields as inputs.FIELD instead of inputs.GROUP.FIELD.',
    items: 'The fields in this group.',
    size: 'The header’s font size, in pixels.',
    text: 'The header’s text.',
    bold: 'Show the header in bold.',
    title: 'The heading at the top of this page.',
    nextLabel: 'The text of the button to the next page. The default is Next.',
    prevLabel: 'The text of the button to the previous page. The default is Previous.',
    clusterName:
      'The Kubernetes cluster to list from. Pick a Kubernetes cluster input, or type a cluster’s name.',
    namespace: 'The namespace to list from. Pick a namespace input, or type its name.',
    csp: 'Which cloud to list from: aws, azure, google or openstack. Or pick the input where users choose it.',
    region: 'The region to list from. Pick a region input, or type its name.',
    provider:
      'Show only clusters of these types, separated by commas, such as aws-slurm or existing.',
    multi: 'Let users pick more than one.',
    multiStep:
      'Lets the person running the workflow add copies of this page. Its fields’ values become a list under the page’s name, one row per copy.',
    minCopies:
      'The fewest copies of a repeatable page. It starts with this many, and no copy can be removed below it.',
    maxCopies:
      'The most copies of a repeatable page. Once it has this many, no more can be added. Set to the same as the minimum, the number is fixed.',
    includeWorkspace: 'Also offer the user’s own workspace.',
    includeUnprovisioned: 'Also offer clusters that aren’t running yet.',
    generateCredentials: 'Create credentials for the bucket and pass them to the run with it.',
    resource: 'The input where users pick the cluster to list from.',
    account:
      'The input where users pick the Slurm account. Only what that account can use is listed.',
    partition:
      'The input where users pick the Slurm partition. Only what that partition allows is listed.',
    includeEmpty: 'Add an empty choice at the top of the list.',
  },
}

export type InputsEditorStrings = typeof INPUTS_EDITOR_STRINGS

/** The graph editor's strings: the host's translations over the English defaults. */
export function useGraphEditorStrings(): GraphEditorStrings {
  const overrides = useStrings().graphEditor
  return useMemo(() => ({ ...GRAPH_EDITOR_STRINGS, ...overrides }), [overrides])
}

/** The input form editor's strings: the host's translations over the English defaults. */
export function useInputsEditorStrings(): InputsEditorStrings {
  const overrides = useStrings().inputsEditor
  return useMemo(() => ({ ...INPUTS_EDITOR_STRINGS, ...overrides }), [overrides])
}
